In [3]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3],[6,7,8]])
print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [6 7 8]]


In [7]:
#creating a array of zeros
arr_zeros = np.zeros((4,5))
print(arr_zeros)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
#creating a array of ones
arr_ones= np.ones((4,5))
print(arr_ones)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:

import numpy as np
#creating an array with random values
arr_random = np.random.rand(3,3)
print(arr_random)


[[0.0645497  0.59397176 0.59714086]
 [0.95290698 0.65777261 0.76751296]
 [0.25558722 0.74541734 0.29075135]]


In [13]:
#creating an array with range of values
arr_range = np.arange(2,20,2)
print(arr_range)

[ 2  4  6  8 10 12 14 16 18]


In [17]:
#element wise addition
arr1=np.array([1,2,3,4,5])

arr1=arr1+2
print(arr1)

[3 4 5 6 7]


In [18]:
#element wise multiplication
arr1=np.array([1,2,3,4,5])

arr1=arr1*2
print(arr1)

[ 2  4  6  8 10]


In [24]:
arr1=np.array([1,2,3,4,5])
print(arr1)
arr2=np.sqrt(arr1)
print(arr2)
arr3=np.exp(arr1)
print(arr3)
arr4=np.log(arr1)
print(arr4)

[1 2 3 4 5]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [25]:
#slicing array
arr1=np.array([1,2,3,4,5])
print(arr1[2:4])

[3 4]


In [29]:
#advanced indexing
arr1=np.array([1,2,3,4,5])
print(arr1[arr1>2])
print(arr1[arr1%2==0])
print(arr1[[0,2,3]])
print(arr1[np.array([True,False,True,False,True])])
print(arr1[arr1<3])


[3 4 5]
[2 4]
[1 3 4]
[1 3 5]
[1 2]


In [41]:
#reshaping
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print(arr1.reshape(2,4))
#transposing the array
print(arr1.T)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [43]:
#aggregation of data
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1.sum())
print(arr1.min())
print(arr1.max())
print(arr1.mean())
#sum along coloums
print(np.sum(arr1,axis=0))
#sum along rows
print(np.sum(arr1,axis=1))

36
1
8
4.5
[ 6  8 10 12]
[10 26]


In [44]:
#index of minimum value
print(arr1.argmin())
#index of maximum value
print(arr1.argmax())


0
7
